<html>
<head>
  <title>条款14：审慎使用异常规格</title>
  <basefont face="微软雅黑" size="2" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="exporter-version" content="Evernote Windows/307027 (zh-CN, DDL); Windows/6.1.0 (Win64);"/>
  <style>
    body, td {
      font-family: 微软雅黑;
      font-size: 10pt;
    }
  </style>
</head>
<body>
<a name="1556"/>
<h1>条款14：审慎使用异常规格</h1>

<div>
<span><div><span style="font-size: 14pt;">条款14：审慎使用异常规格</span></div><div><br/></div><div>如果一个函数抛出一个不在异常规格范围里的异常，系统在运行时能够检测出这个错误，然后一个特殊函数 unexpected 将被自动地调用。</div><div>编译器仅仅部分地检测异常的使用是否与异常规格保持一致。一个函数调用了另一个函数，并且后者可能抛出一个违反前者异常规格的异常，（A 函数调用 B 函数，但因为 B 函数可能抛出一个不在 A 函数异常规格之内的异常，所以这个函数调用就违反了A函数的异常规格  译者注）编译器不对此种情况进行检测，并且语言标准也禁止编译器拒绝这种调用方式（尽管可以显示警告信息）。</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div>extern void f1(); //可以抛出任意异常</div><div>void f2() throw(int);//只能抛出int异常</div><div>void f2() throw(int)</div><div>{</div><div><span>    f1(); //即使f1可能不抛出int类型的异常，这也是合法的</span></div><div>}</div></div><div><br/></div><div>因为你的编译器允许你调用一个函数，其抛出的异常与发出调用的函数的异常规格不一致，并且这样的调用可能导致你的程序执行被终止，所以在编写软件时应该采取措施把这种不一致减小到最少。</div><div><br/></div><div>（1）不要在带有类型参数的模板内使用异常规格</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">template&lt;class T&gt;</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">bool operator==(const T&amp; lhs, const T&amp; rhs) throw()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> <span>    </span> return &amp;lhs == &amp;rhs;</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div></div><div>因为operator&amp;可能被一些类型重载，当调用从 operator==函数内部调用opertor&amp;时，opertor&amp;可能会抛出一个异常，</div><div>这样就违反了我们的异常规格，使得程序控制跳转到unexpected。</div><div>因为我们不知道模板类型抛出什么异常，几乎不可能提供一个有意义的异常规格，好的方法就是不使用。</div><div><br/></div><div>（2）如果在一个函数内调用其它没有异常规格的函数时应该去除这个函数的异常规格</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div>//回调函数</div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">typedef void (*CallBackPtr)(int eventXLocation,</span><span style="font-family: Monaco; font-size: 9pt;"> int eventYLocation,</span><span style="font-family: Monaco; font-size: 9pt;">void *dataToPassBack);</span></div><div><span style="font-family: Monaco; font-size: 9pt;"><br/></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">class CallBack {</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"><span>    </span>public:</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> <span>    </span> CallBack(CallBackPtr fPtr, void *dataToPassBack)</span><span style="font-family: Monaco; font-size: 9pt;">: func(fPtr), data(dataToPassBack) {}</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"><span>    </span>  void makeCallBack(int eventXLocation, </span><span style="font-family: Monaco; font-size: 9pt;">int eventYLocation) const throw();</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"><span>    </span>private:</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> <span>    </span> CallBackPtr func; </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"><span>    </span>   void *data; </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">};               </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void CallBack::makeCallBack(int eventXLocation,</span><span style="font-family: Monaco; font-size: 9pt;">int eventYLocation) const throw()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"><span>    </span>  func(eventXLocation, eventYLocation, data);</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">//违反异常规格的缝隙，因为func会抛出未知类型异常</span></div></div><div><br/></div><div>解决方法是CallBackPtr typedef采取更严格的异常规格</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">typedef void (*CallBackPtr)(int eventXLocation,</span><span style="font-family: Monaco; font-size: 9pt;">int eventYLocation,</span><span style="font-family: Monaco; font-size: 9pt;">void *dataToPassBack) throw();</span></div><div><span style="font-family: Monaco; font-size: 9pt;"><br/></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">// 一个没有异常规格的回调函数</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void callBackFcn1(int eventXLocation, int eventYLocation,</span><span style="font-family: Monaco; font-size: 9pt;">void *dataToPassBack);</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void *callBackData;</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">CallBack c1(callBackFcn1, callBackData);//<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">错误！callBackFcn1可能<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> 抛出异常</span></span></span></div><div><br/></div><div><br/></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void callBackFcn2(int eventXLocation,</span><span style="font-family: Monaco; font-size: 9pt;"> int eventYLocation,</span><span style="font-family: Monaco; font-size: 9pt;">void *dataToPassBack) throw();</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">CallBack c2(callBackFcn2, callBackData);//<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">正确，callBackFcn2，<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">没有异常规格</span></span></span></div></div><div><br/></div><div>（3）处理系统本身抛出的异常</div><div>例如使用new操作符，可能遇到bad_alloc异常。</div><div><br/></div><div>虽然防止抛出 unexpected 异常是不现实的，但是 C++允许你用其它不同的异常类型替换 unexpected异常。</div><div>将所有的unexpected异常替换为UnexpectedException对象。</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">class UnexpectedException {};          // 所有的unexpected异常对象被<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">替换为这种类型对象</span></span></div><div><br/></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void convertUnexpected() // 如果一个 unexpected 异常被<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">抛出，这个函数被调用</span></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  throw UnexpectedException();   </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">set_unexpected(convertUnexpected);</span></div></div><div><br/></div></span>
</div></body></html> 